# Generated by Django 3.2.12 on 2022-03-17 12:15

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us', ckeditor.fields.RichTextField()),
                ('disclaimer', ckeditor.fields.RichTextField()),
                ('terms_and_conditions', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
