# Generated by Django 3.1.4 on 2022-03-11 00:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='terms_and_conditions',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
