# Generated by Django 3.2.12 on 2022-04-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_siteslide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteslide',
            name='action_text',
            field=models.CharField(blank=True, help_text='The text that shows inside the slide button', max_length=50),
        ),
        migrations.AlterField(
            model_name='siteslide',
            name='action_url',
            field=models.URLField(blank=True, help_text='the link that the button should go to.'),
        ),
    ]
