# Generated by Django 3.1.4 on 2022-03-05 00:29

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0004_alter_taggeditem_content_type_alter_taggeditem_tag'),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investmentopportunity',
            options={'ordering': ('-last_modified',), 'verbose_name_plural': 'Investment Opportunities'},
        ),
        migrations.AddField(
            model_name='investmentopportunity',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='investmentopportunity',
            name='url',
            field=models.URLField(default='https://jotimall.com'),
            preserve_default=False,
        ),
    ]
