# Generated by Django 3.1.4 on 2022-03-11 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='picture',
            field=models.ImageField(default='product_images/MV7N2.jpg', upload_to='users/%Y/'),
            preserve_default=False,
        ),
    ]
