# Generated by Django 3.2.12 on 2022-03-15 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_article_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='categories',
        ),
    ]
