# Generated by Django 3.2.12 on 2022-06-10 01:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('label', models.CharField(max_length=100)),
                ('capital', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('industry', models.CharField(blank=True, max_length=50)),
                ('sector', models.CharField(blank=True, max_length=50)),
                ('telephone', models.CharField(blank=True, help_text='phone numbers seperated by comma and space', max_length=100)),
                ('shares', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('slug', models.SlugField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('website', models.URLField(blank=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='StockEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('closing_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('closing_bid_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('price_change', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('closing_offer_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('total_shares_traded', models.PositiveIntegerField(default=0)),
                ('total_value_traded', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_entries', to='stocks.company')),
            ],
            options={
                'ordering': ('-date', 'company'),
            },
        ),
    ]
