# Generated by Django 3.2.12 on 2022-07-21 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_portfolio_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliostock',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='stocks.portfolio'),
        ),
    ]
