# Generated by Django 3.2.12 on 2022-03-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('source', models.CharField(max_length=100)),
                ('url_to_image', models.URLField()),
                ('url', models.URLField()),
                ('published_at', models.DateTimeField()),
            ],
            options={
                'ordering': ('-published_at',),
            },
        ),
    ]
