# Generated by Django 3.2.12 on 2022-03-26 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessnews',
            name='url',
            field=models.URLField(max_length=300),
        ),
        migrations.AlterField(
            model_name='businessnews',
            name='url_to_image',
            field=models.URLField(max_length=300),
        ),
    ]
